# Generated by Django 4.1.4 on 2023-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKENDapp', '0002_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('PRIZE', models.IntegerField(blank=True, null=True)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
                ('SPECIFICATION', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='PRDCT')),
            ],
        ),
    ]
