# Generated by Django 4.1.5 on 2023-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKENDapp', '0005_alter_productdb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=100, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
