# Generated by Django 4.1.3 on 2023-02-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKENDapp', '0008_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to='cart'),
        ),
    ]
