# Generated by Django 4.1.3 on 2023-02-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKENDapp', '0009_cartdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='IMAGE',
        ),
    ]
