# Generated by Django 4.1.5 on 2023-01-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weblogindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('PASSWRD', models.CharField(blank=True, max_length=50, null=True)),
                ('CMFPASSWRD', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
