# Generated by Django 4.1.5 on 2023-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COUNTRY', models.CharField(blank=True, max_length=50, null=True)),
                ('FEEDBACK', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
